language: node_js

node_js:stable

sudo:false

cache:
  apt:true
  directories:
    -node_modules

install:
  -npm install -D
  -cd ./test/smoke/template
  -npm install -D
scripts:
  -npm test

after_script:
  - git config user.name "Zoinlia"
  - git config user.email "1353219143@qq.com"
  # 替换同目录下的_config.yml文件中gh_token字符串为travis后台刚才配置的变量，注意此处sed命令用了双引号。单引号无效！
  - sed -i "s/gh_token/${GH_TOKEN}/g" ./_config.yml